version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: trading_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: trading_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  data_ingestion:
    build: ./data_ingestion
    container_name: trading_ingestion
    restart: unless-stopped
    depends_on:
      - postgres_db
    volumes:
      - ./data_ingestion:/app
    environment:
      - PYTHONUNBUFFERED=1
      # Pasamos las credenciales como variables de entorno al script de Python
      - DB_URL=postgresql://admin:adminpassword@postgres_db:5432/trading_db

volumes:
  pgdata: